<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0340" tests="3" failures="1">
  <testsuite name="Root Suite" timestamp="2022-07-05T16:03:00" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="POST /users" timestamp="2022-07-05T16:03:00" tests="0" file="/Users/quentin/Documents/GitHub/ProjetTS/test/auth.test.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Ok" timestamp="2022-07-05T16:03:00" tests="1" file="/Users/quentin/Documents/GitHub/ProjetTS/test/auth.test.js" time="0.0220" failures="0">
    <testcase name="POST /users Ok Strong password" time="0.0200" classname="Strong password">
    </testcase>
  </testsuite>
  <testsuite name="Bad request" timestamp="2022-07-05T16:03:00" tests="1" file="/Users/quentin/Documents/GitHub/ProjetTS/test/auth.test.js" time="0.0060" failures="0">
    <testcase name="POST /users Bad request Poor or medium password" time="0.0060" classname="Poor or medium password">
    </testcase>
  </testsuite>
  <testsuite name="Not found" timestamp="2022-07-05T16:03:00" tests="1" file="/Users/quentin/Documents/GitHub/ProjetTS/test/auth.test.js" time="0.0030" failures="1">
    <testcase name="POST /users Not found 404 error" time="0.0030" classname="404 error">
      <failure message="400 == 404" type="AssertionError"><![CDATA[AssertionError [ERR_ASSERTION]: 400 == 404
    at Context.<anonymous> (test/auth.test.js:41:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)]]></failure>
    </testcase>
  </testsuite>
</testsuites>